# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths /home/sf306/phd_codebase/github/AXIM_snooper/AXIM_snoop/axim_snooper_1.0 [current_fileset]
read_vhdl {
  /home/sf306/phd_codebase/github/AXIM_snooper/AXIM_snoop/axim_snooper_1.0/hdl/axim_snooper_v1_0_S00_AXI.vhd
  /home/sf306/phd_codebase/github/AXIM_snooper/AXIM_snoop/axim_snooper_1.0/hdl/axim_snooper_v1_0.vhd
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/sf306/phd_codebase/github/AXIM_snooper/managed_ip_project/edit_axim_snooper_v1_0.data/wt [current_project]
set_property parent.project_dir /home/sf306/phd_codebase/github/AXIM_snooper/managed_ip_project [current_project]
synth_design -top axim_snooper_v1_0 -part xc7z020clg484-1
write_checkpoint axim_snooper_v1_0.dcp
report_utilization -file axim_snooper_v1_0_utilization_synth.rpt -pb axim_snooper_v1_0_utilization_synth.pb
